### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by Dumbo52** [bermudalocket/nerdUHC#1]
Some comments (in no particular order):

### Naming Conventions
`UpperCamelCase` for class names, `lowerCamelCase` for methods, fields, and variable names, and `UPPER_CASE_WITH_UNDERSCORES` for constants. Not all languages are strict about it, but these conventions are expected when you're writing Java and help to avoid name collision, not to mention making your code easier to read ("oh, so this is a ClassName you're talking about and not a variableName. Got it.").

Case in point: [`nerdUHC#setGameMode(int)`](https://github.com/bermudalocket/nerdUHC/blob/b170cd86975f4e5b30a280042615ae8de374e26f/src/main/java/com/bermudalocket/nerdUHC/nerdUHC.java#L44). We have
```java
ScoreboardHandler.configureScoreboards(gameMode);
```
It's unclear whether `ScoreboardHandler` refers to the class and `configureScoreboards` is a static function or `ScoreboardHandler` is the instance and `configureScoreboards` is an instance method since there's a field of the `nerdUHC` class (which should be renamed `NerdUHC` by the way) named `ScoreboardHandler`. For that reason, the field containing the instance should be renamed `scoreboardHandler` and the same should be done for other names that deviate from the standard.

On the subject of name collision: The parameter name in [`nerdUHC#setGameMode(int)`](https://github.com/bermudalocket/nerdUHC/blob/b170cd86975f4e5b30a280042615ae8de374e26f/src/main/java/com/bermudalocket/nerdUHC/nerdUHC.java#L41) is `gamemode` but the field name is `gameMode`, hence the
```java
gameMode = gamemode;
```
line. Instead I'd suggest keeping both named `gameMode` (or both `gamemode`, just be consistent!) and instead doing
```java
this.gameMode = gameMode
```
(where `this` refers to the current instance of `nerdUHC` you're in).

### Game mode representation
I would represent the game mode stuff with an enum instead of an int. Maybe make an enum called `UHCGameMode` (to avoid confusion with Bukkit's `GameMode` enum) with options `SOLO` and `TEAM`. The reason for enums is that that data type would only be restricted to one of the two options and you don't have to handle the invalid case everywhere you're using game modes. Plus, in [this switch statement](https://github.com/bermudalocket/nerdUHC/blob/b170cd86975f4e5b30a280042615ae8de374e26f/src/main/java/com/bermudalocket/nerdUHC/ScoreboardHandler.java#L82), it's not clear what `0` or `1` mean. When you replace those with `UHCGameMode.SOLO` and `UHCGameMode.TEAM`, it becomes much more clear what's going on.

You might also consider dynamically checking the game mode [during command parsing](https://github.com/bermudalocket/nerdUHC/blob/b170cd86975f4e5b30a280042615ae8de374e26f/src/main/java/com/bermudalocket/nerdUHC/commands/nerdUHCCommandExecutor.java#L29) by using `UHCGameMode.valueOf(modeString)`. That way if you add more game modes, you don't have to update the command handling.

### Hardcoded team names
The [6 hardcoded teams](https://github.com/bermudalocket/nerdUHC/blob/b170cd86975f4e5b30a280042615ae8de374e26f/src/main/java/com/bermudalocket/nerdUHC/ScoreboardHandler.java#L90) are a little shady. That's the kind of thing you'd want to replace with:
```yaml
teams:
  - Red
  - Orange
  - Yellow
  - Green
  - Blue
  - Purple
```
in the config, then read from that when you're registering the scoreboard teams and store them as a list or a map from names to teams. Not sure if you've heard of the DRY (Don't Repeat Yourself) principle, but if you're writing basically the same line more than 2 times, there's probably a better way to do what you're doing.

### Member visibility
It's good practice to make all of the fields of a class `private` to start off with, then increase their visibility as needed later (or just begin by thinking, "will other classes need to know about this field?" and decide when you create the field). Same thing with methods.

The general idea is, you want to limit the number of things someone can do with an instance of your class to only what your class is designed to do. That eliminates all the noise and makes it much easier to do something with an instance because it only has a limited number of public methods available to be called.

It also makes it harder to do unintended things with your instance. For example, take a look at the [`nerdUHG#gameMode`](https://github.com/bermudalocket/nerdUHC/blob/b170cd86975f4e5b30a280042615ae8de374e26f/src/main/java/com/bermudalocket/nerdUHC/nerdUHC.java#L16) field. It's public, so someone can do `plugin.gameMode = 1` when they want to change the game mode. But they really meant to do `plugin.setGameMode(1)` since otherwise the scoreboards don't get reconfigured. So it's best to get rid of the option to change the `gameMode` field directly at all and just make that field private.

It's actually pretty common to take it to the extreme and rarely make _any_ fields public, instead either making getter and setter methods as needed or (better) creating a method that does only the necessary functionality instead of exposing the contents of that field at all. For instance, the [`nerdUHC#ScoreboardHandler`](https://github.com/bermudalocket/nerdUHC/blob/b170cd86975f4e5b30a280042615ae8de374e26f/src/main/java/com/bermudalocket/nerdUHC/nerdUHC.java#L15) field is public, so `ListenForPlayerJoinEvent` [can call](https://github.com/bermudalocket/nerdUHC/blob/b170cd86975f4e5b30a280042615ae8de374e26f/src/main/java/com/bermudalocket/nerdUHC/listeners/ListenForPlayerJoinEvent.java#L24)
```java
plugin.ScoreboardHandler.SetPlayerBoard(e.getPlayer());
```
That works fine, but say you now want to be able to re-add a player to the game by using a command. You have to know to go into `nerdUHC#ScoreboardHandler` and call `SetPlayerBoard` on that instance of `ScoreboardHandler`. What if you later decide you want to do something else in addition when a player is added to the game? Now you'd have to add that in two places (and remember what those two places are)! So instead, you may want to make the `ScoreboardHandler` field private and instead add a `nerdUHC#registerPlayer(Player)` method that sets the player's scoreboard. Now you can register players from anywhere without having to know about the `ScoreboardHandler`, and you can also make changes to how players are registered in the game all in one place.

### Logging
If you end up deciding to log any messages to console, instead of using `System.out.println(...)`, use `plugin.getLogger().info(...)`. That prefixes lines with a timestamp and `[nerdUHC]` in the logs.

### HashMaps
`HashMap`s aren't magic (not in Java at least). They require the `hashCode` method to be implemented on the class used as a key, otherwise they just use the default which means hashing the instance's memory address. Knowing Bukkit, the `hashCode` method probably has been implemented on `Player`. But regardless, the [tag list](https://github.com/bermudalocket/nerdUHC/blob/b170cd86975f4e5b30a280042615ae8de374e26f/src/main/java/com/bermudalocket/nerdUHC/CombatLogger.java#L19) in `CombatLogger` really shouldn't be mapping _player instances_ to timestamps. That might break across player logins (if that actually mattered in this scenario). Instead, this should map either player `UUID`s or `String`s representing those `UUID`s (but `UUID`s are fine since `UUID#hashCode()` is implemented) to timestamps.

### Other things
In [`ScoreboardHandler#ClearBoards()`](https://github.com/bermudalocket/nerdUHC/blob/b170cd86975f4e5b30a280042615ae8de374e26f/src/main/java/com/bermudalocket/nerdUHC/ScoreboardHandler.java#L60), you have:
```java
if (!board.getEntries().isEmpty()) {
	board.getEntries().forEach(entry -> board.resetScores(entry));
}
if (!board.getTeams().isEmpty()) {
	board.getTeams().forEach(team -> team.unregister());
}
if (!board.getObjectives().isEmpty()) {
	board.getObjectives().forEach(objective -> objective.unregister());
}
```
The `isEmpty` checks can be removed. If those collections are empty, then the `forEach` will vacuously do nothing anyway.

In [CombatLogger#TagCombat(Player, Player)](https://github.com/bermudalocket/nerdUHC/blob/b170cd86975f4e5b30a280042615ae8de374e26f/src/main/java/com/bermudalocket/nerdUHC/CombatLogger.java#L25), you have:
```java
if (!taglist.containsKey(player)) {
	taglist.put(player, new Timestamp(System.currentTimeMillis()).getTime() + 30*100);
} else {
	taglist.replace(player, new Timestamp(System.currentTimeMillis()).getTime() + 30*100);
}

if (!taglist.containsKey(combatant)) {
	taglist.put(combatant, new Timestamp(System.currentTimeMillis()).getTime() + 30*100);
} else {
	taglist.replace(combatant, new Timestamp(System.currentTimeMillis()).getTime() + 30*100);
}
```
`Map#put` sets the value regardless of whether it already has the key, so those `tagList.containsKey` checks are unnecessary. You might also want to consider setting a local variable to `System.currentTimeMillis()` and using that for both. The `Timestamp` stuff can be removed.

It also seems like your plan is to use `taglist` to represent the times at which the tag on each player _expires_, and after that expiry players are removed from the map. To check if a player has combat logged, you would later just check if they're in the map. I would argue that that's not the job of this function. When you're logging that a player has been damaged, there's no reason to overcomplicate things and plan in advance for when the entry should expire. Instead, just log the time at which the damage took place. Later when you're checking whether a player has combat logged, just look at the difference between the current time and the time at which the player was damaged and test whether that's below your time threshold. That also means you can remove the [task](https://github.com/bermudalocket/nerdUHC/blob/b170cd86975f4e5b30a280042615ae8de374e26f/src/main/java/com/bermudalocket/nerdUHC/CombatLogger.java#L48) you're running afterward. No reason to remove players from `taglist`, just leave them in and update it when they're damaged.

Also it's spelled "forfeit".

**Comment by bermudalocket** [comment]
Addressed in c367da4cd5619eb9578519f0499712e43e87d4fd
